blank_issues_enabled: true
contact_links:
  - name: DevTools issues
    url: https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/contact
    about: To submit feature requests or bug reports about Microsoft Edge DevTools, contact the DevTools team.
  - name: WebView2 issues
    url: https://github.com/MicrosoftEdge/WebView2Feedback/issues
    about: Use the WebView2Feedback repository to report feedback, submit feature suggestions or bugs about WebView2, search for existing known issues for WebView2, or share tips and best practices.
